--
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность играть с ботом без регистрации
  - Пользователь должен иметь возможность выбирать или создавать игру после регистрации
  - Пользователь должен иметь возможность выбирать разные уровни заданий
  - Пользователь должен иметь возможность выбирать задачи на русском и английском языке
  - Пользователь должен иметь возможность писать код в игре
  - Пользователь должен иметь возможность писать в чате во время игры
  - Пользователь может повторить игру после проигрыша
  - Пользователь должен иметь возможность приводить новых игроков в команду
  - Пользователь должен иметь возможность оставлять отзыв после игры
  - Пользователь после проигрыша может сыграть ещ раз
  - Пользователь может сдаться в игре
  - Пользователь должен иметь возможность видеть свой рейтинг
  - При правильном коде в игре набор тестов должен быть зеленым
  - При неверном коде в игре должно возникать предупреждение

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров (Firefox версия 131.0.3 (64-разрядная), Google Chrome версия 132.0.6834.83 (64-разрядная),Яндекс версия 24.10.4.756 (64-разрядная), Safari версия 17.4.1)
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)

implicit:
 - Сайт должен обрабатывать ошибки в случае сбоя соединения
 - Если на сайте есть усеченный текст, то при наведении курсора мыши должен отображаться весь текст целиком (всплывающая подсказка)
 - При создании игры автоматичкски стоит одна звезда сложности
 - Если в поле есть какая-либо ошибка, то сообщение об ошибке должно начинаться прямо под этим полем
 - Во время разбивки на страницы опция предыдущая должна быть доступна только после страницы 1, а опция следующая страница не должна быть доступна на последней странице
 - Копирование и вставка кода в поле игры или из него не должны быть разрешены
 - Заголовки всех страниц/разделов должны быть оформлены аналогичным образом и иметь одинаковый тип/размер шрифта
 - Цвет и тематика всех подсказок/оповещений на сайте должны быть одинаковыми

