--
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность играть с ботом без регистрации
  - Пользователь должен иметь возможность выбирать или создавать игру после регистрации
  - Пользователь должен иметь возможность выбирать разные уровни заданий
  - Пользователь должен иметь возможность выбирать задачи на русском и английском языке
  - Пользователь должен иметь возможность писать код в игре
  - Пользователь должен иметь возможность писать в чате во время игры
  - Пользователь может повторить игру после проигрыша
  - Пользователь должен иметь возможность приводить новых игроков в команду
  - Пользователь должен иметь возможность оставлять отзыв после игры
  - Пользователь после проигрыша может сыграть ещ раз
  - Пользователь может сдаться в игре
  - Пользователь должен иметь возможность видеть свой рейтинг
  - При правильном коде в игре набор тестов должен быть зеленым
  - При неверном коде в игре должно возникать предупреждение

non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)

implicit:
  - Сайт должен обрабатывать ошибки в случае сбоя соединения
