---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность играть с ботом без регистрации
  - Пользователь должен иметь возможность выбирать или создавать игру после регистрации
  - Пользователь должен иметь возможность выбирать разные уровни заданий
  - Пользователь должен иметь возможность выбирать задачи на русском и английском языке
  - Пользователь должен иметь возможность писать код в игре
  - Пользователь должен иметь возможность писать в чате во время игры
  - Пользователь может повторить игру после проигрыша
  - Пользователь должен иметь возможность приводить новых игроков в команду
  - Пользователь должен иметь возможность оставлять отзыв после игры
  - Пользователь после проигрыша может сыграть ещё раз
  - Пользователь может сдаться в игре
  - Пользователь должен иметь возможность видеть свой рейтинг
  - При правильном коде в игре набор тестов должен быть зеленым
  - При неверном коде в игре должно возникать предупреждение
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров Firefox 131.0.3, Google Chrome 132.0.6834.83,Яндекс 24.10.4.756, Safari 17.4.1
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Сайт должен обрабатывать ошибки в случае сбоя соединения
  - При создании игры автоматически стоит одна звезда сложности
  - Если в поле есть ошибка, то сообщение об ошибке возникает под этим полем
  - Копирование и вставка кода в поле игры не должны быть разрешены
  - Заголовки всех разделов должны быть оформлены одинаково и иметь аналогичный тип и размер шрифта
  - Цвет и тематика всех оповещений должны быть одинаковыми
